#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get  update
sudo apt-get  install nginx
sudo ufw  "Nginx HTTP"
echo "Hello world !" | sudo tee /var/www/html/index.html
sudo ngine -t

sudo service nginx restart
